# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run prettier & lint
    - run: npm install
      run: npx prettier -c ./src
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run jest tests
    - run: npm install
      run: npm run test
